// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docs: [
    {
      type: 'category',
      label: 'Introduction',
      items: [
        'introduction/what-is-bookfusion',
        'introduction/benefits-features',
        'introduction/getting-started',
      ],
    },
    {
      type: 'category',
      label: 'Smart Queries & Smart Shelves',
      link: {
            type: 'doc',
            id: 'smart-queries-shelves/overview',
          },
      items: [
        'smart-queries-shelves/overview',
        'smart-queries-shelves/why-it-matters',
        {
          type: 'category',
          label: 'Smart Queries',
          link: {
            type: 'doc',
            id: 'smart-queries-shelves/smart-queries/what-are-smart-queries',
          },
          items: [
            'smart-queries-shelves/smart-queries/what-are-smart-queries',
            'smart-queries-shelves/smart-queries/query-language',
            'smart-queries-shelves/smart-queries/manual-query-creation',
            'smart-queries-shelves/smart-queries/ui-query-creation',
            'smart-queries-shelves/smart-queries/example-queries',
          ],
        },
        {
          type: 'category',
          label: 'Smart Shelves',
          link: {
            type: 'doc',
            id: 'smart-queries-shelves/smart-shelves/what-are-smart-shelves',
          },
          items: [
            'smart-queries-shelves/smart-shelves/what-are-smart-shelves',
            'smart-queries-shelves/smart-shelves/creating-smart-shelf',
            'smart-queries-shelves/smart-shelves/using-smart-shelf-web',
            'smart-queries-shelves/smart-shelves/using-smart-shelf-mobile',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
